M48
; DRILL file {KiCad 8.0.1} date 2024-06-28T04:06:01+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-28T04:06:01+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X150.22Y-95.0
X150.22Y-122.8
X180.72Y-95.0
T2
X129.0Y-43.65
X129.0Y-143.4
X163.9Y-93.55
M30
